/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdditionalRouteImport } from './routes/additional'
import { Route as ApprovedRouteImport } from './routes/approved'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as DeletedRouteImport } from './routes/deleted'
import { Route as ImportRouteImport } from './routes/import'
import { Route as PlatformsRouteImport } from './routes/platforms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SubmittedRouteImport } from './routes/submitted'
import { Route as SuggestedRouteImport } from './routes/suggested'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as ContentIndexRouteImport } from './routes/content.index'
import { Route as ContentCreateRouteImport } from './routes/content.create'
import { Route as ApiAuthFacebookRouteImport } from './routes/api.auth.facebook'
import { Route as ApiAuthInstagramRouteImport } from './routes/api.auth.instagram'
import { Route as ApiFacebookDeleteRouteImport } from './routes/api.facebook.delete'
import { Route as ApiFacebookEditRouteImport } from './routes/api.facebook.edit'
import { Route as ApiFacebookPhotoRouteImport } from './routes/api.facebook.photo'
import { Route as ApiFacebookPostRouteImport } from './routes/api.facebook.post'
import { Route as ApiFacebookScheduleRouteImport } from './routes/api.facebook.schedule'
import { Route as ApiAuthFacebookCallbackRouteImport } from './routes/api.auth.facebook.callback'
import { Route as ApiAuthInstagramCallbackRouteImport } from './routes/api.auth.instagram.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdditionalRoute = AdditionalRouteImport.update({
  id: '/additional',
  path: '/additional',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovedRoute = ApprovedRouteImport.update({
  id: '/approved',
  path: '/approved',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const DeletedRoute = DeletedRouteImport.update({
  id: '/deleted',
  path: '/deleted',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformsRoute = PlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmittedRoute = SubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestedRoute = SuggestedRouteImport.update({
  id: '/suggested',
  path: '/suggested',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentCreateRoute = ContentCreateRouteImport.update({
  id: '/content/create',
  path: '/content/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthFacebookRoute = ApiAuthFacebookRouteImport.update({
  id: '/api/auth/facebook',
  path: '/api/auth/facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthInstagramRoute = ApiAuthInstagramRouteImport.update({
  id: '/api/auth/instagram',
  path: '/api/auth/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFacebookDeleteRoute = ApiFacebookDeleteRouteImport.update({
  id: '/api/facebook/delete',
  path: '/api/facebook/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFacebookEditRoute = ApiFacebookEditRouteImport.update({
  id: '/api/facebook/edit',
  path: '/api/facebook/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFacebookPhotoRoute = ApiFacebookPhotoRouteImport.update({
  id: '/api/facebook/photo',
  path: '/api/facebook/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFacebookPostRoute = ApiFacebookPostRouteImport.update({
  id: '/api/facebook/post',
  path: '/api/facebook/post',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFacebookScheduleRoute = ApiFacebookScheduleRouteImport.update({
  id: '/api/facebook/schedule',
  path: '/api/facebook/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthFacebookCallbackRoute = ApiAuthFacebookCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthFacebookRoute,
} as any)
const ApiAuthInstagramCallbackRoute =
  ApiAuthInstagramCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => ApiAuthInstagramRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/additional': typeof AdditionalRoute
  '/approved': typeof ApprovedRoute
  '/clients': typeof ClientsRouteWithChildren
  '/deleted': typeof DeletedRoute
  '/import': typeof ImportRoute
  '/platforms': typeof PlatformsRoute
  '/settings': typeof SettingsRoute
  '/submitted': typeof SubmittedRoute
  '/suggested': typeof SuggestedRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/content/create': typeof ContentCreateRoute
  '/content/': typeof ContentIndexRoute
  '/api/auth/facebook': typeof ApiAuthFacebookRouteWithChildren
  '/api/auth/instagram': typeof ApiAuthInstagramRouteWithChildren
  '/api/facebook/delete': typeof ApiFacebookDeleteRoute
  '/api/facebook/edit': typeof ApiFacebookEditRoute
  '/api/facebook/photo': typeof ApiFacebookPhotoRoute
  '/api/facebook/post': typeof ApiFacebookPostRoute
  '/api/facebook/schedule': typeof ApiFacebookScheduleRoute
  '/api/auth/facebook/callback': typeof ApiAuthFacebookCallbackRoute
  '/api/auth/instagram/callback': typeof ApiAuthInstagramCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/additional': typeof AdditionalRoute
  '/approved': typeof ApprovedRoute
  '/clients': typeof ClientsRouteWithChildren
  '/deleted': typeof DeletedRoute
  '/import': typeof ImportRoute
  '/platforms': typeof PlatformsRoute
  '/settings': typeof SettingsRoute
  '/submitted': typeof SubmittedRoute
  '/suggested': typeof SuggestedRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/content/create': typeof ContentCreateRoute
  '/content': typeof ContentIndexRoute
  '/api/auth/facebook': typeof ApiAuthFacebookRouteWithChildren
  '/api/auth/instagram': typeof ApiAuthInstagramRouteWithChildren
  '/api/facebook/delete': typeof ApiFacebookDeleteRoute
  '/api/facebook/edit': typeof ApiFacebookEditRoute
  '/api/facebook/photo': typeof ApiFacebookPhotoRoute
  '/api/facebook/post': typeof ApiFacebookPostRoute
  '/api/facebook/schedule': typeof ApiFacebookScheduleRoute
  '/api/auth/facebook/callback': typeof ApiAuthFacebookCallbackRoute
  '/api/auth/instagram/callback': typeof ApiAuthInstagramCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/additional': typeof AdditionalRoute
  '/approved': typeof ApprovedRoute
  '/clients': typeof ClientsRouteWithChildren
  '/deleted': typeof DeletedRoute
  '/import': typeof ImportRoute
  '/platforms': typeof PlatformsRoute
  '/settings': typeof SettingsRoute
  '/submitted': typeof SubmittedRoute
  '/suggested': typeof SuggestedRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/content/create': typeof ContentCreateRoute
  '/content/': typeof ContentIndexRoute
  '/api/auth/facebook': typeof ApiAuthFacebookRouteWithChildren
  '/api/auth/instagram': typeof ApiAuthInstagramRouteWithChildren
  '/api/facebook/delete': typeof ApiFacebookDeleteRoute
  '/api/facebook/edit': typeof ApiFacebookEditRoute
  '/api/facebook/photo': typeof ApiFacebookPhotoRoute
  '/api/facebook/post': typeof ApiFacebookPostRoute
  '/api/facebook/schedule': typeof ApiFacebookScheduleRoute
  '/api/auth/facebook/callback': typeof ApiAuthFacebookCallbackRoute
  '/api/auth/instagram/callback': typeof ApiAuthInstagramCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/additional'
    | '/approved'
    | '/clients'
    | '/deleted'
    | '/import'
    | '/platforms'
    | '/settings'
    | '/submitted'
    | '/suggested'
    | '/clients/$clientId'
    | '/content/create'
    | '/content/'
    | '/api/auth/facebook'
    | '/api/auth/instagram'
    | '/api/facebook/delete'
    | '/api/facebook/edit'
    | '/api/facebook/photo'
    | '/api/facebook/post'
    | '/api/facebook/schedule'
    | '/api/auth/facebook/callback'
    | '/api/auth/instagram/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/additional'
    | '/approved'
    | '/clients'
    | '/deleted'
    | '/import'
    | '/platforms'
    | '/settings'
    | '/submitted'
    | '/suggested'
    | '/clients/$clientId'
    | '/content/create'
    | '/content'
    | '/api/auth/facebook'
    | '/api/auth/instagram'
    | '/api/facebook/delete'
    | '/api/facebook/edit'
    | '/api/facebook/photo'
    | '/api/facebook/post'
    | '/api/facebook/schedule'
    | '/api/auth/facebook/callback'
    | '/api/auth/instagram/callback'
  id:
    | '__root__'
    | '/'
    | '/additional'
    | '/approved'
    | '/clients'
    | '/deleted'
    | '/import'
    | '/platforms'
    | '/settings'
    | '/submitted'
    | '/suggested'
    | '/clients/$clientId'
    | '/content/create'
    | '/content/'
    | '/api/auth/facebook'
    | '/api/auth/instagram'
    | '/api/facebook/delete'
    | '/api/facebook/edit'
    | '/api/facebook/photo'
    | '/api/facebook/post'
    | '/api/facebook/schedule'
    | '/api/auth/facebook/callback'
    | '/api/auth/instagram/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdditionalRoute: typeof AdditionalRoute
  ApprovedRoute: typeof ApprovedRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  DeletedRoute: typeof DeletedRoute
  ImportRoute: typeof ImportRoute
  PlatformsRoute: typeof PlatformsRoute
  SettingsRoute: typeof SettingsRoute
  SubmittedRoute: typeof SubmittedRoute
  SuggestedRoute: typeof SuggestedRoute
  ContentCreateRoute: typeof ContentCreateRoute
  ContentIndexRoute: typeof ContentIndexRoute
  ApiAuthFacebookRoute: typeof ApiAuthFacebookRouteWithChildren
  ApiAuthInstagramRoute: typeof ApiAuthInstagramRouteWithChildren
  ApiFacebookDeleteRoute: typeof ApiFacebookDeleteRoute
  ApiFacebookEditRoute: typeof ApiFacebookEditRoute
  ApiFacebookPhotoRoute: typeof ApiFacebookPhotoRoute
  ApiFacebookPostRoute: typeof ApiFacebookPostRoute
  ApiFacebookScheduleRoute: typeof ApiFacebookScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/additional': {
      id: '/additional'
      path: '/additional'
      fullPath: '/additional'
      preLoaderRoute: typeof AdditionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approved': {
      id: '/approved'
      path: '/approved'
      fullPath: '/approved'
      preLoaderRoute: typeof ApprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deleted': {
      id: '/deleted'
      path: '/deleted'
      fullPath: '/deleted'
      preLoaderRoute: typeof DeletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforms': {
      id: '/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof PlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submitted': {
      id: '/submitted'
      path: '/submitted'
      fullPath: '/submitted'
      preLoaderRoute: typeof SubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggested': {
      id: '/suggested'
      path: '/suggested'
      fullPath: '/suggested'
      preLoaderRoute: typeof SuggestedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/content/': {
      id: '/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/create': {
      id: '/content/create'
      path: '/content/create'
      fullPath: '/content/create'
      preLoaderRoute: typeof ContentCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/facebook': {
      id: '/api/auth/facebook'
      path: '/api/auth/facebook'
      fullPath: '/api/auth/facebook'
      preLoaderRoute: typeof ApiAuthFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/instagram': {
      id: '/api/auth/instagram'
      path: '/api/auth/instagram'
      fullPath: '/api/auth/instagram'
      preLoaderRoute: typeof ApiAuthInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facebook/delete': {
      id: '/api/facebook/delete'
      path: '/api/facebook/delete'
      fullPath: '/api/facebook/delete'
      preLoaderRoute: typeof ApiFacebookDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facebook/edit': {
      id: '/api/facebook/edit'
      path: '/api/facebook/edit'
      fullPath: '/api/facebook/edit'
      preLoaderRoute: typeof ApiFacebookEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facebook/photo': {
      id: '/api/facebook/photo'
      path: '/api/facebook/photo'
      fullPath: '/api/facebook/photo'
      preLoaderRoute: typeof ApiFacebookPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facebook/post': {
      id: '/api/facebook/post'
      path: '/api/facebook/post'
      fullPath: '/api/facebook/post'
      preLoaderRoute: typeof ApiFacebookPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facebook/schedule': {
      id: '/api/facebook/schedule'
      path: '/api/facebook/schedule'
      fullPath: '/api/facebook/schedule'
      preLoaderRoute: typeof ApiFacebookScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/facebook/callback': {
      id: '/api/auth/facebook/callback'
      path: '/callback'
      fullPath: '/api/auth/facebook/callback'
      preLoaderRoute: typeof ApiAuthFacebookCallbackRouteImport
      parentRoute: typeof ApiAuthFacebookRoute
    }
    '/api/auth/instagram/callback': {
      id: '/api/auth/instagram/callback'
      path: '/callback'
      fullPath: '/api/auth/instagram/callback'
      preLoaderRoute: typeof ApiAuthInstagramCallbackRouteImport
      parentRoute: typeof ApiAuthInstagramRoute
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface ApiAuthFacebookRouteChildren {
  ApiAuthFacebookCallbackRoute: typeof ApiAuthFacebookCallbackRoute
}

const ApiAuthFacebookRouteChildren: ApiAuthFacebookRouteChildren = {
  ApiAuthFacebookCallbackRoute: ApiAuthFacebookCallbackRoute,
}

const ApiAuthFacebookRouteWithChildren = ApiAuthFacebookRoute._addFileChildren(
  ApiAuthFacebookRouteChildren,
)

interface ApiAuthInstagramRouteChildren {
  ApiAuthInstagramCallbackRoute: typeof ApiAuthInstagramCallbackRoute
}

const ApiAuthInstagramRouteChildren: ApiAuthInstagramRouteChildren = {
  ApiAuthInstagramCallbackRoute: ApiAuthInstagramCallbackRoute,
}

const ApiAuthInstagramRouteWithChildren =
  ApiAuthInstagramRoute._addFileChildren(ApiAuthInstagramRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdditionalRoute: AdditionalRoute,
  ApprovedRoute: ApprovedRoute,
  ClientsRoute: ClientsRouteWithChildren,
  DeletedRoute: DeletedRoute,
  ImportRoute: ImportRoute,
  PlatformsRoute: PlatformsRoute,
  SettingsRoute: SettingsRoute,
  SubmittedRoute: SubmittedRoute,
  SuggestedRoute: SuggestedRoute,
  ContentCreateRoute: ContentCreateRoute,
  ContentIndexRoute: ContentIndexRoute,
  ApiAuthFacebookRoute: ApiAuthFacebookRouteWithChildren,
  ApiAuthInstagramRoute: ApiAuthInstagramRouteWithChildren,
  ApiFacebookDeleteRoute: ApiFacebookDeleteRoute,
  ApiFacebookEditRoute: ApiFacebookEditRoute,
  ApiFacebookPhotoRoute: ApiFacebookPhotoRoute,
  ApiFacebookPostRoute: ApiFacebookPostRoute,
  ApiFacebookScheduleRoute: ApiFacebookScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
