/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdditionalRouteImport } from './routes/additional'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApprovedRouteImport } from './routes/approved'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeletedRouteImport } from './routes/deleted'
import { Route as ExportRouteImport } from './routes/export'
import { Route as ImportRouteImport } from './routes/import'
import { Route as PlatformsRouteImport } from './routes/platforms'
import { Route as PreviewDemoRouteImport } from './routes/preview-demo'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SubmittedRouteImport } from './routes/submitted'
import { Route as SuggestedRouteImport } from './routes/suggested'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ClientTokenRouteImport } from './routes/client.$token'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as ContentIndexRouteImport } from './routes/content.index'
import { Route as ContentCreateRouteImport } from './routes/content.create'
import { Route as ApiAiDescribeImageRouteImport } from './routes/api.ai.describe-image'
import { Route as ApiAiGenerateCaptionRouteImport } from './routes/api.ai.generate-caption'
import { Route as ApiAiGenerateCarouselRouteImport } from './routes/api.ai.generate-carousel'
import { Route as ApiAiGenerateHashtagsRouteImport } from './routes/api.ai.generate-hashtags'
import { Route as ApiAiGenerateImageRouteImport } from './routes/api.ai.generate-image'
import { Route as ApiAiGenerateImagePromptRouteImport } from './routes/api.ai.generate-image-prompt'
import { Route as ApiAiResearchTrendsRouteImport } from './routes/api.ai.research-trends'
import { Route as ApiAiStrategizeRouteImport } from './routes/api.ai.strategize'
import { Route as ApiAiWriteCaptionRouteImport } from './routes/api.ai.write-caption'
import { Route as ApiAuthFacebookRouteImport } from './routes/api.auth.facebook'
import { Route as ApiAuthGbpRouteImport } from './routes/api.auth.gbp'
import { Route as ApiAuthInstagramRouteImport } from './routes/api.auth.instagram'
import { Route as ApiAuthInstagramDirectRouteImport } from './routes/api.auth.instagram-direct'
import { Route as ApiFacebookDeleteRouteImport } from './routes/api.facebook.delete'
import { Route as ApiFacebookEditRouteImport } from './routes/api.facebook.edit'
import { Route as ApiFacebookPhotoRouteImport } from './routes/api.facebook.photo'
import { Route as ApiFacebookPostRouteImport } from './routes/api.facebook.post'
import { Route as ApiFacebookRefreshTokenRouteImport } from './routes/api.facebook.refresh-token'
import { Route as ApiFacebookScheduleRouteImport } from './routes/api.facebook.schedule'
import { Route as ApiFacebookValidateTokenRouteImport } from './routes/api.facebook.validate-token'
import { Route as ApiGbpPostRouteImport } from './routes/api.gbp.post'
import { Route as ApiGbpRefreshTokenRouteImport } from './routes/api.gbp.refresh-token'
import { Route as ApiInstagramPostRouteImport } from './routes/api.instagram.post'
import { Route as ApiInstagramScheduleRouteImport } from './routes/api.instagram.schedule'
import { Route as ApiWebhookInstagramRouteImport } from './routes/api.webhook.instagram'
import { Route as ApiAuthFacebookCallbackRouteImport } from './routes/api.auth.facebook.callback'
import { Route as ApiAuthGbpCallbackRouteImport } from './routes/api.auth.gbp.callback'
import { Route as ApiAuthInstagramDirectCallbackRouteImport } from './routes/api.auth.instagram-direct.callback'
import { Route as ApiAuthInstagramCallbackRouteImport } from './routes/api.auth.instagram.callback'
import { Route as ApiAuthInstagramFacebookRouteImport } from './routes/api.auth.instagram.facebook'
import { Route as ApiAuthInstagramFacebookCallbackRouteImport } from './routes/api.auth.instagram.facebook.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdditionalRoute = AdditionalRouteImport.update({
  id: '/additional',
  path: '/additional',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovedRoute = ApprovedRouteImport.update({
  id: '/approved',
  path: '/approved',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeletedRoute = DeletedRouteImport.update({
  id: '/deleted',
  path: '/deleted',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformsRoute = PlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewDemoRoute = PreviewDemoRouteImport.update({
  id: '/preview-demo',
  path: '/preview-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmittedRoute = SubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestedRoute = SuggestedRouteImport.update({
  id: '/suggested',
  path: '/suggested',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientTokenRoute = ClientTokenRouteImport.update({
  id: '/client/$token',
  path: '/client/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentCreateRoute = ContentCreateRouteImport.update({
  id: '/content/create',
  path: '/content/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiDescribeImageRoute = ApiAiDescribeImageRouteImport.update({
  id: '/api/ai/describe-image',
  path: '/api/ai/describe-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateCaptionRoute = ApiAiGenerateCaptionRouteImport.update({
  id: '/api/ai/generate-caption',
  path: '/api/ai/generate-caption',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateCarouselRoute = ApiAiGenerateCarouselRouteImport.update({
  id: '/api/ai/generate-carousel',
  path: '/api/ai/generate-carousel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateHashtagsRoute = ApiAiGenerateHashtagsRouteImport.update({
  id: '/api/ai/generate-hashtags',
  path: '/api/ai/generate-hashtags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateImageRoute = ApiAiGenerateImageRouteImport.update({
  id: '/api/ai/generate-image',
  path: '/api/ai/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateImagePromptRoute =
  ApiAiGenerateImagePromptRouteImport.update({
    id: '/api/ai/generate-image-prompt',
    path: '/api/ai/generate-image-prompt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiResearchTrendsRoute = ApiAiResearchTrendsRouteImport.update({
  id: '/api/ai/research-trends',
  path: '/api/ai/research-trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiStrategizeRoute = ApiAiStrategizeRouteImport.update({
  id: '/api/ai/strategize',
  path: '/api/ai/strategize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiWriteCaptionRoute = ApiAiWriteCaptionRouteImport.update({
  id: '/api/ai/write-caption',
  path: '/api/ai/write-caption',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthFacebookRoute = ApiAuthFacebookRouteImport.update({
  id: '/api/auth/facebook',
  path: '/api/auth/facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGbpRoute = ApiAuthGbpRouteImport.update({
  id: '/api/auth/gbp',
  path: '/api/auth/gbp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthInstagramRoute = ApiAuthInstagramRouteImport.update({
  id: '/api/auth/instagram',
  path: '/api/auth/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthInstagramDirectRoute = ApiAuthInstagramDirectRouteImport.update({
  id: '/api/auth/instagram-direct',
  path: '/api/auth/instagram-direct',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFacebookDeleteRoute = ApiFacebookDeleteRouteImport.update({
  id: '/api/facebook/delete',
  path: '/api/facebook/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFacebookEditRoute = ApiFacebookEditRouteImport.update({
  id: '/api/facebook/edit',
  path: '/api/facebook/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFacebookPhotoRoute = ApiFacebookPhotoRouteImport.update({
  id: '/api/facebook/photo',
  path: '/api/facebook/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFacebookPostRoute = ApiFacebookPostRouteImport.update({
  id: '/api/facebook/post',
  path: '/api/facebook/post',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFacebookRefreshTokenRoute = ApiFacebookRefreshTokenRouteImport.update({
  id: '/api/facebook/refresh-token',
  path: '/api/facebook/refresh-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFacebookScheduleRoute = ApiFacebookScheduleRouteImport.update({
  id: '/api/facebook/schedule',
  path: '/api/facebook/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFacebookValidateTokenRoute =
  ApiFacebookValidateTokenRouteImport.update({
    id: '/api/facebook/validate-token',
    path: '/api/facebook/validate-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGbpPostRoute = ApiGbpPostRouteImport.update({
  id: '/api/gbp/post',
  path: '/api/gbp/post',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGbpRefreshTokenRoute = ApiGbpRefreshTokenRouteImport.update({
  id: '/api/gbp/refresh-token',
  path: '/api/gbp/refresh-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstagramPostRoute = ApiInstagramPostRouteImport.update({
  id: '/api/instagram/post',
  path: '/api/instagram/post',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstagramScheduleRoute = ApiInstagramScheduleRouteImport.update({
  id: '/api/instagram/schedule',
  path: '/api/instagram/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookInstagramRoute = ApiWebhookInstagramRouteImport.update({
  id: '/api/webhook/instagram',
  path: '/api/webhook/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthFacebookCallbackRoute = ApiAuthFacebookCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthFacebookRoute,
} as any)
const ApiAuthGbpCallbackRoute = ApiAuthGbpCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGbpRoute,
} as any)
const ApiAuthInstagramDirectCallbackRoute =
  ApiAuthInstagramDirectCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => ApiAuthInstagramDirectRoute,
  } as any)
const ApiAuthInstagramCallbackRoute =
  ApiAuthInstagramCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => ApiAuthInstagramRoute,
  } as any)
const ApiAuthInstagramFacebookRoute =
  ApiAuthInstagramFacebookRouteImport.update({
    id: '/facebook',
    path: '/facebook',
    getParentRoute: () => ApiAuthInstagramRoute,
  } as any)
const ApiAuthInstagramFacebookCallbackRoute =
  ApiAuthInstagramFacebookCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => ApiAuthInstagramFacebookRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/additional': typeof AdditionalRoute
  '/analytics': typeof AnalyticsRoute
  '/approved': typeof ApprovedRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/deleted': typeof DeletedRoute
  '/export': typeof ExportRoute
  '/import': typeof ImportRoute
  '/platforms': typeof PlatformsRoute
  '/preview-demo': typeof PreviewDemoRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/submitted': typeof SubmittedRoute
  '/suggested': typeof SuggestedRoute
  '/users': typeof UsersRoute
  '/client/$token': typeof ClientTokenRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/content/create': typeof ContentCreateRoute
  '/content/': typeof ContentIndexRoute
  '/api/ai/describe-image': typeof ApiAiDescribeImageRoute
  '/api/ai/generate-caption': typeof ApiAiGenerateCaptionRoute
  '/api/ai/generate-carousel': typeof ApiAiGenerateCarouselRoute
  '/api/ai/generate-hashtags': typeof ApiAiGenerateHashtagsRoute
  '/api/ai/generate-image': typeof ApiAiGenerateImageRoute
  '/api/ai/generate-image-prompt': typeof ApiAiGenerateImagePromptRoute
  '/api/ai/research-trends': typeof ApiAiResearchTrendsRoute
  '/api/ai/strategize': typeof ApiAiStrategizeRoute
  '/api/ai/write-caption': typeof ApiAiWriteCaptionRoute
  '/api/auth/facebook': typeof ApiAuthFacebookRouteWithChildren
  '/api/auth/gbp': typeof ApiAuthGbpRouteWithChildren
  '/api/auth/instagram': typeof ApiAuthInstagramRouteWithChildren
  '/api/auth/instagram-direct': typeof ApiAuthInstagramDirectRouteWithChildren
  '/api/facebook/delete': typeof ApiFacebookDeleteRoute
  '/api/facebook/edit': typeof ApiFacebookEditRoute
  '/api/facebook/photo': typeof ApiFacebookPhotoRoute
  '/api/facebook/post': typeof ApiFacebookPostRoute
  '/api/facebook/refresh-token': typeof ApiFacebookRefreshTokenRoute
  '/api/facebook/schedule': typeof ApiFacebookScheduleRoute
  '/api/facebook/validate-token': typeof ApiFacebookValidateTokenRoute
  '/api/gbp/post': typeof ApiGbpPostRoute
  '/api/gbp/refresh-token': typeof ApiGbpRefreshTokenRoute
  '/api/instagram/post': typeof ApiInstagramPostRoute
  '/api/instagram/schedule': typeof ApiInstagramScheduleRoute
  '/api/webhook/instagram': typeof ApiWebhookInstagramRoute
  '/api/auth/facebook/callback': typeof ApiAuthFacebookCallbackRoute
  '/api/auth/gbp/callback': typeof ApiAuthGbpCallbackRoute
  '/api/auth/instagram-direct/callback': typeof ApiAuthInstagramDirectCallbackRoute
  '/api/auth/instagram/callback': typeof ApiAuthInstagramCallbackRoute
  '/api/auth/instagram/facebook': typeof ApiAuthInstagramFacebookRouteWithChildren
  '/api/auth/instagram/facebook/callback': typeof ApiAuthInstagramFacebookCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/additional': typeof AdditionalRoute
  '/analytics': typeof AnalyticsRoute
  '/approved': typeof ApprovedRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/deleted': typeof DeletedRoute
  '/export': typeof ExportRoute
  '/import': typeof ImportRoute
  '/platforms': typeof PlatformsRoute
  '/preview-demo': typeof PreviewDemoRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/submitted': typeof SubmittedRoute
  '/suggested': typeof SuggestedRoute
  '/users': typeof UsersRoute
  '/client/$token': typeof ClientTokenRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/content/create': typeof ContentCreateRoute
  '/content': typeof ContentIndexRoute
  '/api/ai/describe-image': typeof ApiAiDescribeImageRoute
  '/api/ai/generate-caption': typeof ApiAiGenerateCaptionRoute
  '/api/ai/generate-carousel': typeof ApiAiGenerateCarouselRoute
  '/api/ai/generate-hashtags': typeof ApiAiGenerateHashtagsRoute
  '/api/ai/generate-image': typeof ApiAiGenerateImageRoute
  '/api/ai/generate-image-prompt': typeof ApiAiGenerateImagePromptRoute
  '/api/ai/research-trends': typeof ApiAiResearchTrendsRoute
  '/api/ai/strategize': typeof ApiAiStrategizeRoute
  '/api/ai/write-caption': typeof ApiAiWriteCaptionRoute
  '/api/auth/facebook': typeof ApiAuthFacebookRouteWithChildren
  '/api/auth/gbp': typeof ApiAuthGbpRouteWithChildren
  '/api/auth/instagram': typeof ApiAuthInstagramRouteWithChildren
  '/api/auth/instagram-direct': typeof ApiAuthInstagramDirectRouteWithChildren
  '/api/facebook/delete': typeof ApiFacebookDeleteRoute
  '/api/facebook/edit': typeof ApiFacebookEditRoute
  '/api/facebook/photo': typeof ApiFacebookPhotoRoute
  '/api/facebook/post': typeof ApiFacebookPostRoute
  '/api/facebook/refresh-token': typeof ApiFacebookRefreshTokenRoute
  '/api/facebook/schedule': typeof ApiFacebookScheduleRoute
  '/api/facebook/validate-token': typeof ApiFacebookValidateTokenRoute
  '/api/gbp/post': typeof ApiGbpPostRoute
  '/api/gbp/refresh-token': typeof ApiGbpRefreshTokenRoute
  '/api/instagram/post': typeof ApiInstagramPostRoute
  '/api/instagram/schedule': typeof ApiInstagramScheduleRoute
  '/api/webhook/instagram': typeof ApiWebhookInstagramRoute
  '/api/auth/facebook/callback': typeof ApiAuthFacebookCallbackRoute
  '/api/auth/gbp/callback': typeof ApiAuthGbpCallbackRoute
  '/api/auth/instagram-direct/callback': typeof ApiAuthInstagramDirectCallbackRoute
  '/api/auth/instagram/callback': typeof ApiAuthInstagramCallbackRoute
  '/api/auth/instagram/facebook': typeof ApiAuthInstagramFacebookRouteWithChildren
  '/api/auth/instagram/facebook/callback': typeof ApiAuthInstagramFacebookCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/additional': typeof AdditionalRoute
  '/analytics': typeof AnalyticsRoute
  '/approved': typeof ApprovedRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/deleted': typeof DeletedRoute
  '/export': typeof ExportRoute
  '/import': typeof ImportRoute
  '/platforms': typeof PlatformsRoute
  '/preview-demo': typeof PreviewDemoRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/submitted': typeof SubmittedRoute
  '/suggested': typeof SuggestedRoute
  '/users': typeof UsersRoute
  '/client/$token': typeof ClientTokenRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/content/create': typeof ContentCreateRoute
  '/content/': typeof ContentIndexRoute
  '/api/ai/describe-image': typeof ApiAiDescribeImageRoute
  '/api/ai/generate-caption': typeof ApiAiGenerateCaptionRoute
  '/api/ai/generate-carousel': typeof ApiAiGenerateCarouselRoute
  '/api/ai/generate-hashtags': typeof ApiAiGenerateHashtagsRoute
  '/api/ai/generate-image': typeof ApiAiGenerateImageRoute
  '/api/ai/generate-image-prompt': typeof ApiAiGenerateImagePromptRoute
  '/api/ai/research-trends': typeof ApiAiResearchTrendsRoute
  '/api/ai/strategize': typeof ApiAiStrategizeRoute
  '/api/ai/write-caption': typeof ApiAiWriteCaptionRoute
  '/api/auth/facebook': typeof ApiAuthFacebookRouteWithChildren
  '/api/auth/gbp': typeof ApiAuthGbpRouteWithChildren
  '/api/auth/instagram': typeof ApiAuthInstagramRouteWithChildren
  '/api/auth/instagram-direct': typeof ApiAuthInstagramDirectRouteWithChildren
  '/api/facebook/delete': typeof ApiFacebookDeleteRoute
  '/api/facebook/edit': typeof ApiFacebookEditRoute
  '/api/facebook/photo': typeof ApiFacebookPhotoRoute
  '/api/facebook/post': typeof ApiFacebookPostRoute
  '/api/facebook/refresh-token': typeof ApiFacebookRefreshTokenRoute
  '/api/facebook/schedule': typeof ApiFacebookScheduleRoute
  '/api/facebook/validate-token': typeof ApiFacebookValidateTokenRoute
  '/api/gbp/post': typeof ApiGbpPostRoute
  '/api/gbp/refresh-token': typeof ApiGbpRefreshTokenRoute
  '/api/instagram/post': typeof ApiInstagramPostRoute
  '/api/instagram/schedule': typeof ApiInstagramScheduleRoute
  '/api/webhook/instagram': typeof ApiWebhookInstagramRoute
  '/api/auth/facebook/callback': typeof ApiAuthFacebookCallbackRoute
  '/api/auth/gbp/callback': typeof ApiAuthGbpCallbackRoute
  '/api/auth/instagram-direct/callback': typeof ApiAuthInstagramDirectCallbackRoute
  '/api/auth/instagram/callback': typeof ApiAuthInstagramCallbackRoute
  '/api/auth/instagram/facebook': typeof ApiAuthInstagramFacebookRouteWithChildren
  '/api/auth/instagram/facebook/callback': typeof ApiAuthInstagramFacebookCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/additional'
    | '/analytics'
    | '/approved'
    | '/auth'
    | '/calendar'
    | '/clients'
    | '/dashboard'
    | '/deleted'
    | '/export'
    | '/import'
    | '/platforms'
    | '/preview-demo'
    | '/privacy'
    | '/settings'
    | '/submitted'
    | '/suggested'
    | '/users'
    | '/client/$token'
    | '/clients/$clientId'
    | '/content/create'
    | '/content/'
    | '/api/ai/describe-image'
    | '/api/ai/generate-caption'
    | '/api/ai/generate-carousel'
    | '/api/ai/generate-hashtags'
    | '/api/ai/generate-image'
    | '/api/ai/generate-image-prompt'
    | '/api/ai/research-trends'
    | '/api/ai/strategize'
    | '/api/ai/write-caption'
    | '/api/auth/facebook'
    | '/api/auth/gbp'
    | '/api/auth/instagram'
    | '/api/auth/instagram-direct'
    | '/api/facebook/delete'
    | '/api/facebook/edit'
    | '/api/facebook/photo'
    | '/api/facebook/post'
    | '/api/facebook/refresh-token'
    | '/api/facebook/schedule'
    | '/api/facebook/validate-token'
    | '/api/gbp/post'
    | '/api/gbp/refresh-token'
    | '/api/instagram/post'
    | '/api/instagram/schedule'
    | '/api/webhook/instagram'
    | '/api/auth/facebook/callback'
    | '/api/auth/gbp/callback'
    | '/api/auth/instagram-direct/callback'
    | '/api/auth/instagram/callback'
    | '/api/auth/instagram/facebook'
    | '/api/auth/instagram/facebook/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/additional'
    | '/analytics'
    | '/approved'
    | '/auth'
    | '/calendar'
    | '/clients'
    | '/dashboard'
    | '/deleted'
    | '/export'
    | '/import'
    | '/platforms'
    | '/preview-demo'
    | '/privacy'
    | '/settings'
    | '/submitted'
    | '/suggested'
    | '/users'
    | '/client/$token'
    | '/clients/$clientId'
    | '/content/create'
    | '/content'
    | '/api/ai/describe-image'
    | '/api/ai/generate-caption'
    | '/api/ai/generate-carousel'
    | '/api/ai/generate-hashtags'
    | '/api/ai/generate-image'
    | '/api/ai/generate-image-prompt'
    | '/api/ai/research-trends'
    | '/api/ai/strategize'
    | '/api/ai/write-caption'
    | '/api/auth/facebook'
    | '/api/auth/gbp'
    | '/api/auth/instagram'
    | '/api/auth/instagram-direct'
    | '/api/facebook/delete'
    | '/api/facebook/edit'
    | '/api/facebook/photo'
    | '/api/facebook/post'
    | '/api/facebook/refresh-token'
    | '/api/facebook/schedule'
    | '/api/facebook/validate-token'
    | '/api/gbp/post'
    | '/api/gbp/refresh-token'
    | '/api/instagram/post'
    | '/api/instagram/schedule'
    | '/api/webhook/instagram'
    | '/api/auth/facebook/callback'
    | '/api/auth/gbp/callback'
    | '/api/auth/instagram-direct/callback'
    | '/api/auth/instagram/callback'
    | '/api/auth/instagram/facebook'
    | '/api/auth/instagram/facebook/callback'
  id:
    | '__root__'
    | '/'
    | '/additional'
    | '/analytics'
    | '/approved'
    | '/auth'
    | '/calendar'
    | '/clients'
    | '/dashboard'
    | '/deleted'
    | '/export'
    | '/import'
    | '/platforms'
    | '/preview-demo'
    | '/privacy'
    | '/settings'
    | '/submitted'
    | '/suggested'
    | '/users'
    | '/client/$token'
    | '/clients/$clientId'
    | '/content/create'
    | '/content/'
    | '/api/ai/describe-image'
    | '/api/ai/generate-caption'
    | '/api/ai/generate-carousel'
    | '/api/ai/generate-hashtags'
    | '/api/ai/generate-image'
    | '/api/ai/generate-image-prompt'
    | '/api/ai/research-trends'
    | '/api/ai/strategize'
    | '/api/ai/write-caption'
    | '/api/auth/facebook'
    | '/api/auth/gbp'
    | '/api/auth/instagram'
    | '/api/auth/instagram-direct'
    | '/api/facebook/delete'
    | '/api/facebook/edit'
    | '/api/facebook/photo'
    | '/api/facebook/post'
    | '/api/facebook/refresh-token'
    | '/api/facebook/schedule'
    | '/api/facebook/validate-token'
    | '/api/gbp/post'
    | '/api/gbp/refresh-token'
    | '/api/instagram/post'
    | '/api/instagram/schedule'
    | '/api/webhook/instagram'
    | '/api/auth/facebook/callback'
    | '/api/auth/gbp/callback'
    | '/api/auth/instagram-direct/callback'
    | '/api/auth/instagram/callback'
    | '/api/auth/instagram/facebook'
    | '/api/auth/instagram/facebook/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdditionalRoute: typeof AdditionalRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovedRoute: typeof ApprovedRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DeletedRoute: typeof DeletedRoute
  ExportRoute: typeof ExportRoute
  ImportRoute: typeof ImportRoute
  PlatformsRoute: typeof PlatformsRoute
  PreviewDemoRoute: typeof PreviewDemoRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  SubmittedRoute: typeof SubmittedRoute
  SuggestedRoute: typeof SuggestedRoute
  UsersRoute: typeof UsersRoute
  ClientTokenRoute: typeof ClientTokenRoute
  ContentCreateRoute: typeof ContentCreateRoute
  ContentIndexRoute: typeof ContentIndexRoute
  ApiAiDescribeImageRoute: typeof ApiAiDescribeImageRoute
  ApiAiGenerateCaptionRoute: typeof ApiAiGenerateCaptionRoute
  ApiAiGenerateCarouselRoute: typeof ApiAiGenerateCarouselRoute
  ApiAiGenerateHashtagsRoute: typeof ApiAiGenerateHashtagsRoute
  ApiAiGenerateImageRoute: typeof ApiAiGenerateImageRoute
  ApiAiGenerateImagePromptRoute: typeof ApiAiGenerateImagePromptRoute
  ApiAiResearchTrendsRoute: typeof ApiAiResearchTrendsRoute
  ApiAiStrategizeRoute: typeof ApiAiStrategizeRoute
  ApiAiWriteCaptionRoute: typeof ApiAiWriteCaptionRoute
  ApiAuthFacebookRoute: typeof ApiAuthFacebookRouteWithChildren
  ApiAuthGbpRoute: typeof ApiAuthGbpRouteWithChildren
  ApiAuthInstagramRoute: typeof ApiAuthInstagramRouteWithChildren
  ApiAuthInstagramDirectRoute: typeof ApiAuthInstagramDirectRouteWithChildren
  ApiFacebookDeleteRoute: typeof ApiFacebookDeleteRoute
  ApiFacebookEditRoute: typeof ApiFacebookEditRoute
  ApiFacebookPhotoRoute: typeof ApiFacebookPhotoRoute
  ApiFacebookPostRoute: typeof ApiFacebookPostRoute
  ApiFacebookRefreshTokenRoute: typeof ApiFacebookRefreshTokenRoute
  ApiFacebookScheduleRoute: typeof ApiFacebookScheduleRoute
  ApiFacebookValidateTokenRoute: typeof ApiFacebookValidateTokenRoute
  ApiGbpPostRoute: typeof ApiGbpPostRoute
  ApiGbpRefreshTokenRoute: typeof ApiGbpRefreshTokenRoute
  ApiInstagramPostRoute: typeof ApiInstagramPostRoute
  ApiInstagramScheduleRoute: typeof ApiInstagramScheduleRoute
  ApiWebhookInstagramRoute: typeof ApiWebhookInstagramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/additional': {
      id: '/additional'
      path: '/additional'
      fullPath: '/additional'
      preLoaderRoute: typeof AdditionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approved': {
      id: '/approved'
      path: '/approved'
      fullPath: '/approved'
      preLoaderRoute: typeof ApprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deleted': {
      id: '/deleted'
      path: '/deleted'
      fullPath: '/deleted'
      preLoaderRoute: typeof DeletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforms': {
      id: '/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof PlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-demo': {
      id: '/preview-demo'
      path: '/preview-demo'
      fullPath: '/preview-demo'
      preLoaderRoute: typeof PreviewDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submitted': {
      id: '/submitted'
      path: '/submitted'
      fullPath: '/submitted'
      preLoaderRoute: typeof SubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggested': {
      id: '/suggested'
      path: '/suggested'
      fullPath: '/suggested'
      preLoaderRoute: typeof SuggestedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/$token': {
      id: '/client/$token'
      path: '/client/$token'
      fullPath: '/client/$token'
      preLoaderRoute: typeof ClientTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/content/': {
      id: '/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/create': {
      id: '/content/create'
      path: '/content/create'
      fullPath: '/content/create'
      preLoaderRoute: typeof ContentCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/describe-image': {
      id: '/api/ai/describe-image'
      path: '/api/ai/describe-image'
      fullPath: '/api/ai/describe-image'
      preLoaderRoute: typeof ApiAiDescribeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-caption': {
      id: '/api/ai/generate-caption'
      path: '/api/ai/generate-caption'
      fullPath: '/api/ai/generate-caption'
      preLoaderRoute: typeof ApiAiGenerateCaptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-carousel': {
      id: '/api/ai/generate-carousel'
      path: '/api/ai/generate-carousel'
      fullPath: '/api/ai/generate-carousel'
      preLoaderRoute: typeof ApiAiGenerateCarouselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-hashtags': {
      id: '/api/ai/generate-hashtags'
      path: '/api/ai/generate-hashtags'
      fullPath: '/api/ai/generate-hashtags'
      preLoaderRoute: typeof ApiAiGenerateHashtagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-image': {
      id: '/api/ai/generate-image'
      path: '/api/ai/generate-image'
      fullPath: '/api/ai/generate-image'
      preLoaderRoute: typeof ApiAiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-image-prompt': {
      id: '/api/ai/generate-image-prompt'
      path: '/api/ai/generate-image-prompt'
      fullPath: '/api/ai/generate-image-prompt'
      preLoaderRoute: typeof ApiAiGenerateImagePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/research-trends': {
      id: '/api/ai/research-trends'
      path: '/api/ai/research-trends'
      fullPath: '/api/ai/research-trends'
      preLoaderRoute: typeof ApiAiResearchTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/strategize': {
      id: '/api/ai/strategize'
      path: '/api/ai/strategize'
      fullPath: '/api/ai/strategize'
      preLoaderRoute: typeof ApiAiStrategizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/write-caption': {
      id: '/api/ai/write-caption'
      path: '/api/ai/write-caption'
      fullPath: '/api/ai/write-caption'
      preLoaderRoute: typeof ApiAiWriteCaptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/facebook': {
      id: '/api/auth/facebook'
      path: '/api/auth/facebook'
      fullPath: '/api/auth/facebook'
      preLoaderRoute: typeof ApiAuthFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/gbp': {
      id: '/api/auth/gbp'
      path: '/api/auth/gbp'
      fullPath: '/api/auth/gbp'
      preLoaderRoute: typeof ApiAuthGbpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/instagram': {
      id: '/api/auth/instagram'
      path: '/api/auth/instagram'
      fullPath: '/api/auth/instagram'
      preLoaderRoute: typeof ApiAuthInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/instagram-direct': {
      id: '/api/auth/instagram-direct'
      path: '/api/auth/instagram-direct'
      fullPath: '/api/auth/instagram-direct'
      preLoaderRoute: typeof ApiAuthInstagramDirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facebook/delete': {
      id: '/api/facebook/delete'
      path: '/api/facebook/delete'
      fullPath: '/api/facebook/delete'
      preLoaderRoute: typeof ApiFacebookDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facebook/edit': {
      id: '/api/facebook/edit'
      path: '/api/facebook/edit'
      fullPath: '/api/facebook/edit'
      preLoaderRoute: typeof ApiFacebookEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facebook/photo': {
      id: '/api/facebook/photo'
      path: '/api/facebook/photo'
      fullPath: '/api/facebook/photo'
      preLoaderRoute: typeof ApiFacebookPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facebook/post': {
      id: '/api/facebook/post'
      path: '/api/facebook/post'
      fullPath: '/api/facebook/post'
      preLoaderRoute: typeof ApiFacebookPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facebook/refresh-token': {
      id: '/api/facebook/refresh-token'
      path: '/api/facebook/refresh-token'
      fullPath: '/api/facebook/refresh-token'
      preLoaderRoute: typeof ApiFacebookRefreshTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facebook/schedule': {
      id: '/api/facebook/schedule'
      path: '/api/facebook/schedule'
      fullPath: '/api/facebook/schedule'
      preLoaderRoute: typeof ApiFacebookScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facebook/validate-token': {
      id: '/api/facebook/validate-token'
      path: '/api/facebook/validate-token'
      fullPath: '/api/facebook/validate-token'
      preLoaderRoute: typeof ApiFacebookValidateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gbp/post': {
      id: '/api/gbp/post'
      path: '/api/gbp/post'
      fullPath: '/api/gbp/post'
      preLoaderRoute: typeof ApiGbpPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gbp/refresh-token': {
      id: '/api/gbp/refresh-token'
      path: '/api/gbp/refresh-token'
      fullPath: '/api/gbp/refresh-token'
      preLoaderRoute: typeof ApiGbpRefreshTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/instagram/post': {
      id: '/api/instagram/post'
      path: '/api/instagram/post'
      fullPath: '/api/instagram/post'
      preLoaderRoute: typeof ApiInstagramPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/instagram/schedule': {
      id: '/api/instagram/schedule'
      path: '/api/instagram/schedule'
      fullPath: '/api/instagram/schedule'
      preLoaderRoute: typeof ApiInstagramScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/instagram': {
      id: '/api/webhook/instagram'
      path: '/api/webhook/instagram'
      fullPath: '/api/webhook/instagram'
      preLoaderRoute: typeof ApiWebhookInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/facebook/callback': {
      id: '/api/auth/facebook/callback'
      path: '/callback'
      fullPath: '/api/auth/facebook/callback'
      preLoaderRoute: typeof ApiAuthFacebookCallbackRouteImport
      parentRoute: typeof ApiAuthFacebookRoute
    }
    '/api/auth/gbp/callback': {
      id: '/api/auth/gbp/callback'
      path: '/callback'
      fullPath: '/api/auth/gbp/callback'
      preLoaderRoute: typeof ApiAuthGbpCallbackRouteImport
      parentRoute: typeof ApiAuthGbpRoute
    }
    '/api/auth/instagram-direct/callback': {
      id: '/api/auth/instagram-direct/callback'
      path: '/callback'
      fullPath: '/api/auth/instagram-direct/callback'
      preLoaderRoute: typeof ApiAuthInstagramDirectCallbackRouteImport
      parentRoute: typeof ApiAuthInstagramDirectRoute
    }
    '/api/auth/instagram/callback': {
      id: '/api/auth/instagram/callback'
      path: '/callback'
      fullPath: '/api/auth/instagram/callback'
      preLoaderRoute: typeof ApiAuthInstagramCallbackRouteImport
      parentRoute: typeof ApiAuthInstagramRoute
    }
    '/api/auth/instagram/facebook': {
      id: '/api/auth/instagram/facebook'
      path: '/facebook'
      fullPath: '/api/auth/instagram/facebook'
      preLoaderRoute: typeof ApiAuthInstagramFacebookRouteImport
      parentRoute: typeof ApiAuthInstagramRoute
    }
    '/api/auth/instagram/facebook/callback': {
      id: '/api/auth/instagram/facebook/callback'
      path: '/callback'
      fullPath: '/api/auth/instagram/facebook/callback'
      preLoaderRoute: typeof ApiAuthInstagramFacebookCallbackRouteImport
      parentRoute: typeof ApiAuthInstagramFacebookRoute
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface ApiAuthFacebookRouteChildren {
  ApiAuthFacebookCallbackRoute: typeof ApiAuthFacebookCallbackRoute
}

const ApiAuthFacebookRouteChildren: ApiAuthFacebookRouteChildren = {
  ApiAuthFacebookCallbackRoute: ApiAuthFacebookCallbackRoute,
}

const ApiAuthFacebookRouteWithChildren = ApiAuthFacebookRoute._addFileChildren(
  ApiAuthFacebookRouteChildren,
)

interface ApiAuthGbpRouteChildren {
  ApiAuthGbpCallbackRoute: typeof ApiAuthGbpCallbackRoute
}

const ApiAuthGbpRouteChildren: ApiAuthGbpRouteChildren = {
  ApiAuthGbpCallbackRoute: ApiAuthGbpCallbackRoute,
}

const ApiAuthGbpRouteWithChildren = ApiAuthGbpRoute._addFileChildren(
  ApiAuthGbpRouteChildren,
)

interface ApiAuthInstagramFacebookRouteChildren {
  ApiAuthInstagramFacebookCallbackRoute: typeof ApiAuthInstagramFacebookCallbackRoute
}

const ApiAuthInstagramFacebookRouteChildren: ApiAuthInstagramFacebookRouteChildren =
  {
    ApiAuthInstagramFacebookCallbackRoute:
      ApiAuthInstagramFacebookCallbackRoute,
  }

const ApiAuthInstagramFacebookRouteWithChildren =
  ApiAuthInstagramFacebookRoute._addFileChildren(
    ApiAuthInstagramFacebookRouteChildren,
  )

interface ApiAuthInstagramRouteChildren {
  ApiAuthInstagramCallbackRoute: typeof ApiAuthInstagramCallbackRoute
  ApiAuthInstagramFacebookRoute: typeof ApiAuthInstagramFacebookRouteWithChildren
}

const ApiAuthInstagramRouteChildren: ApiAuthInstagramRouteChildren = {
  ApiAuthInstagramCallbackRoute: ApiAuthInstagramCallbackRoute,
  ApiAuthInstagramFacebookRoute: ApiAuthInstagramFacebookRouteWithChildren,
}

const ApiAuthInstagramRouteWithChildren =
  ApiAuthInstagramRoute._addFileChildren(ApiAuthInstagramRouteChildren)

interface ApiAuthInstagramDirectRouteChildren {
  ApiAuthInstagramDirectCallbackRoute: typeof ApiAuthInstagramDirectCallbackRoute
}

const ApiAuthInstagramDirectRouteChildren: ApiAuthInstagramDirectRouteChildren =
  {
    ApiAuthInstagramDirectCallbackRoute: ApiAuthInstagramDirectCallbackRoute,
  }

const ApiAuthInstagramDirectRouteWithChildren =
  ApiAuthInstagramDirectRoute._addFileChildren(
    ApiAuthInstagramDirectRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdditionalRoute: AdditionalRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovedRoute: ApprovedRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  ClientsRoute: ClientsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DeletedRoute: DeletedRoute,
  ExportRoute: ExportRoute,
  ImportRoute: ImportRoute,
  PlatformsRoute: PlatformsRoute,
  PreviewDemoRoute: PreviewDemoRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  SubmittedRoute: SubmittedRoute,
  SuggestedRoute: SuggestedRoute,
  UsersRoute: UsersRoute,
  ClientTokenRoute: ClientTokenRoute,
  ContentCreateRoute: ContentCreateRoute,
  ContentIndexRoute: ContentIndexRoute,
  ApiAiDescribeImageRoute: ApiAiDescribeImageRoute,
  ApiAiGenerateCaptionRoute: ApiAiGenerateCaptionRoute,
  ApiAiGenerateCarouselRoute: ApiAiGenerateCarouselRoute,
  ApiAiGenerateHashtagsRoute: ApiAiGenerateHashtagsRoute,
  ApiAiGenerateImageRoute: ApiAiGenerateImageRoute,
  ApiAiGenerateImagePromptRoute: ApiAiGenerateImagePromptRoute,
  ApiAiResearchTrendsRoute: ApiAiResearchTrendsRoute,
  ApiAiStrategizeRoute: ApiAiStrategizeRoute,
  ApiAiWriteCaptionRoute: ApiAiWriteCaptionRoute,
  ApiAuthFacebookRoute: ApiAuthFacebookRouteWithChildren,
  ApiAuthGbpRoute: ApiAuthGbpRouteWithChildren,
  ApiAuthInstagramRoute: ApiAuthInstagramRouteWithChildren,
  ApiAuthInstagramDirectRoute: ApiAuthInstagramDirectRouteWithChildren,
  ApiFacebookDeleteRoute: ApiFacebookDeleteRoute,
  ApiFacebookEditRoute: ApiFacebookEditRoute,
  ApiFacebookPhotoRoute: ApiFacebookPhotoRoute,
  ApiFacebookPostRoute: ApiFacebookPostRoute,
  ApiFacebookRefreshTokenRoute: ApiFacebookRefreshTokenRoute,
  ApiFacebookScheduleRoute: ApiFacebookScheduleRoute,
  ApiFacebookValidateTokenRoute: ApiFacebookValidateTokenRoute,
  ApiGbpPostRoute: ApiGbpPostRoute,
  ApiGbpRefreshTokenRoute: ApiGbpRefreshTokenRoute,
  ApiInstagramPostRoute: ApiInstagramPostRoute,
  ApiInstagramScheduleRoute: ApiInstagramScheduleRoute,
  ApiWebhookInstagramRoute: ApiWebhookInstagramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
