/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PercakapanRouteImport } from './routes/percakapan'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as OtomatisasiRouteImport } from './routes/otomatisasi'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChannelRouteImport } from './routes/channel'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackendIndexRouteImport } from './routes/backend/index'
import { Route as BackendLoginRouteImport } from './routes/backend/login'
import { Route as BackendDashboardRouteImport } from './routes/backend/dashboard'
import { Route as BackendChatsRouteImport } from './routes/backend/chats'
import { Route as BackendInstancesRouteImport } from './routes/backend/instances'
import { Route as BackendScheduledRouteImport } from './routes/backend/scheduled'
import { Route as BackendSettingsRouteImport } from './routes/backend/settings'
import { Route as BackendUsersRouteImport } from './routes/backend/users'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PercakapanRoute = PercakapanRouteImport.update({
  id: '/percakapan',
  path: '/percakapan',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const OtomatisasiRoute = OtomatisasiRouteImport.update({
  id: '/otomatisasi',
  path: '/otomatisasi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelRoute = ChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendIndexRoute = BackendIndexRouteImport.update({
  id: '/backend/',
  path: '/backend/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendLoginRoute = BackendLoginRouteImport.update({
  id: '/backend/login',
  path: '/backend/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendDashboardRoute = BackendDashboardRouteImport.update({
  id: '/backend/dashboard',
  path: '/backend/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendChatsRoute = BackendChatsRouteImport.update({
  id: '/backend/chats',
  path: '/backend/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendInstancesRoute = BackendInstancesRouteImport.update({
  id: '/backend/instances',
  path: '/backend/instances',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendScheduledRoute = BackendScheduledRouteImport.update({
  id: '/backend/scheduled',
  path: '/backend/scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendSettingsRoute = BackendSettingsRouteImport.update({
  id: '/backend/settings',
  path: '/backend/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendUsersRoute = BackendUsersRouteImport.update({
  id: '/backend/users',
  path: '/backend/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/channel': typeof ChannelRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/otomatisasi': typeof OtomatisasiRoute
  '/pengaturan': typeof PengaturanRoute
  '/percakapan': typeof PercakapanRoute
  '/profil': typeof ProfilRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/backend/chats': typeof BackendChatsRoute
  '/backend/dashboard': typeof BackendDashboardRoute
  '/backend/instances': typeof BackendInstancesRoute
  '/backend/login': typeof BackendLoginRoute
  '/backend/scheduled': typeof BackendScheduledRoute
  '/backend/settings': typeof BackendSettingsRoute
  '/backend/users': typeof BackendUsersRoute
  '/backend/': typeof BackendIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/channel': typeof ChannelRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/otomatisasi': typeof OtomatisasiRoute
  '/pengaturan': typeof PengaturanRoute
  '/percakapan': typeof PercakapanRoute
  '/profil': typeof ProfilRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/backend/chats': typeof BackendChatsRoute
  '/backend/dashboard': typeof BackendDashboardRoute
  '/backend/instances': typeof BackendInstancesRoute
  '/backend/login': typeof BackendLoginRoute
  '/backend/scheduled': typeof BackendScheduledRoute
  '/backend/settings': typeof BackendSettingsRoute
  '/backend/users': typeof BackendUsersRoute
  '/backend': typeof BackendIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/channel': typeof ChannelRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/otomatisasi': typeof OtomatisasiRoute
  '/pengaturan': typeof PengaturanRoute
  '/percakapan': typeof PercakapanRoute
  '/profil': typeof ProfilRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/backend/chats': typeof BackendChatsRoute
  '/backend/dashboard': typeof BackendDashboardRoute
  '/backend/instances': typeof BackendInstancesRoute
  '/backend/login': typeof BackendLoginRoute
  '/backend/scheduled': typeof BackendScheduledRoute
  '/backend/settings': typeof BackendSettingsRoute
  '/backend/users': typeof BackendUsersRoute
  '/backend/': typeof BackendIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/channel'
    | '/dashboard'
    | '/knowledge'
    | '/login'
    | '/otomatisasi'
    | '/pengaturan'
    | '/percakapan'
    | '/profil'
    | '/signup'
    | '/auth/callback'
    | '/backend/chats'
    | '/backend/dashboard'
    | '/backend/instances'
    | '/backend/login'
    | '/backend/scheduled'
    | '/backend/settings'
    | '/backend/users'
    | '/backend/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/channel'
    | '/dashboard'
    | '/knowledge'
    | '/login'
    | '/otomatisasi'
    | '/pengaturan'
    | '/percakapan'
    | '/profil'
    | '/signup'
    | '/auth/callback'
    | '/backend/chats'
    | '/backend/dashboard'
    | '/backend/instances'
    | '/backend/login'
    | '/backend/scheduled'
    | '/backend/settings'
    | '/backend/users'
    | '/backend'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/channel'
    | '/dashboard'
    | '/knowledge'
    | '/login'
    | '/otomatisasi'
    | '/pengaturan'
    | '/percakapan'
    | '/profil'
    | '/signup'
    | '/auth/callback'
    | '/backend/chats'
    | '/backend/dashboard'
    | '/backend/instances'
    | '/backend/login'
    | '/backend/scheduled'
    | '/backend/settings'
    | '/backend/users'
    | '/backend/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ChannelRoute: typeof ChannelRoute
  DashboardRoute: typeof DashboardRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  OtomatisasiRoute: typeof OtomatisasiRoute
  PengaturanRoute: typeof PengaturanRoute
  PercakapanRoute: typeof PercakapanRoute
  ProfilRoute: typeof ProfilRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BackendChatsRoute: typeof BackendChatsRoute
  BackendDashboardRoute: typeof BackendDashboardRoute
  BackendInstancesRoute: typeof BackendInstancesRoute
  BackendLoginRoute: typeof BackendLoginRoute
  BackendScheduledRoute: typeof BackendScheduledRoute
  BackendSettingsRoute: typeof BackendSettingsRoute
  BackendUsersRoute: typeof BackendUsersRoute
  BackendIndexRoute: typeof BackendIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/percakapan': {
      id: '/percakapan'
      path: '/percakapan'
      fullPath: '/percakapan'
      preLoaderRoute: typeof PercakapanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otomatisasi': {
      id: '/otomatisasi'
      path: '/otomatisasi'
      fullPath: '/otomatisasi'
      preLoaderRoute: typeof OtomatisasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel': {
      id: '/channel'
      path: '/channel'
      fullPath: '/channel'
      preLoaderRoute: typeof ChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend/': {
      id: '/backend/'
      path: '/backend'
      fullPath: '/backend/'
      preLoaderRoute: typeof BackendIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend/login': {
      id: '/backend/login'
      path: '/backend/login'
      fullPath: '/backend/login'
      preLoaderRoute: typeof BackendLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend/chats': {
      id: '/backend/chats'
      path: '/backend/chats'
      fullPath: '/backend/chats'
      preLoaderRoute: typeof BackendChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend/dashboard': {
      id: '/backend/dashboard'
      path: '/backend/dashboard'
      fullPath: '/backend/dashboard'
      preLoaderRoute: typeof BackendDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend/instances': {
      id: '/backend/instances'
      path: '/backend/instances'
      fullPath: '/backend/instances'
      preLoaderRoute: typeof BackendInstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend/scheduled': {
      id: '/backend/scheduled'
      path: '/backend/scheduled'
      fullPath: '/backend/scheduled'
      preLoaderRoute: typeof BackendScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend/settings': {
      id: '/backend/settings'
      path: '/backend/settings'
      fullPath: '/backend/settings'
      preLoaderRoute: typeof BackendSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend/users': {
      id: '/backend/users'
      path: '/backend/users'
      fullPath: '/backend/users'
      preLoaderRoute: typeof BackendUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ChannelRoute: ChannelRoute,
  DashboardRoute: DashboardRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  OtomatisasiRoute: OtomatisasiRoute,
  PengaturanRoute: PengaturanRoute,
  PercakapanRoute: PercakapanRoute,
  ProfilRoute: ProfilRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BackendChatsRoute: BackendChatsRoute,
  BackendDashboardRoute: BackendDashboardRoute,
  BackendInstancesRoute: BackendInstancesRoute,
  BackendLoginRoute: BackendLoginRoute,
  BackendScheduledRoute: BackendScheduledRoute,
  BackendSettingsRoute: BackendSettingsRoute,
  BackendUsersRoute: BackendUsersRoute,
  BackendIndexRoute: BackendIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
